![Nuclio logo](https://nuclio.school/wp-content/uploads/2018/12/nucleoDS-newBlack.png)

# Exercícios - NumPy Arrays

Neste notebook, encontram 20 exercícios que vos permitirão aprender as bases acerca de NumPy Arrays.

1 - Importe a biblioteca numpy.

In [1]:
import numpy as np

2 - Crie um numpy array com valores inteiros entre 0 e 9.

In [8]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


3 - Extraia todos os números pares do array que criou anteriormente.

In [9]:
array_even = arr[arr % 2 == 0]
print(array_even)

[0 2 4 6 8]


4 - Substitua todos os números pares por zero.

In [10]:
arr[arr % 2 == 0] = 0
print(arr)

[0 1 0 3 0 5 0 7 0 9]


5 - Modifique o array para que este passe a ser um array 2D com 5 rows.

In [12]:
arr.reshape([5, 2]) # cada row deve ter 2 elementos


array([[0, 1],
       [0, 3],
       [0, 5],
       [0, 7],
       [0, 9]])

6 - Dados dois arrays:

a = np.array([1, 2, 3, 4, 4, 1, 2, 5, 5, 6])

b = np.array([7, 2, 8, 4, 4, 0, 9, 4, 9, 0])

Verifique os elementos comuns entre ambos arrays (valor e posição iguais) e crie um array com o resultado (sem elementos duplicados).

In [15]:
a = np.array([1, 2, 3, 4, 4, 1, 2, 5, 5, 6])

b = np.array([7, 2, 8, 4, 4, 0, 9, 4, 9, 0])

In [16]:
a[a == b]

array([2, 4, 4])

In [17]:
np.unique(a[a==b])


array([2, 4])

7 - Elimine do array a todos os elementos que também estão presentes em b.

In [19]:
print(a[a != b])
print(np.unique(a[a != b]))

#segunda opção
#print(a[np.isin(a,b) == False])
#print(np.unique(a[np.isin(a,b) == False]))


[1 3 1 2 5 5 6]
[1 2 3 5 6]
[1 3 1 5 5 6]
[1 3 5 6]


8 - Returne um array com as posições dos elementos do array a que são comuns ao array b.

In [20]:
a

array([1, 2, 3, 4, 4, 1, 2, 5, 5, 6])

In [21]:
np.where(a == b)

(array([1, 3, 4]),)

9 - Crie um array 4x4 com elementos entre 0 e 15.

In [26]:
arr = np.array(np.arange(16))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
my_arr = arr.reshape([4,4])
my_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

10 - Troque a ordem das colunas 2 e 3 do array anterior.

In [28]:
col1 = my_arr[:,2].copy()
col2 = my_arr[:,3].copy()



In [29]:
my_arr[:,2], my_arr[:,3] = col2, col1
my_arr

array([[ 0,  1,  3,  2],
       [ 4,  5,  7,  6],
       [ 8,  9, 11, 10],
       [12, 13, 15, 14]])

11 - Troque as rows 1 e 2 do array anterior.

In [30]:
row1 = my_arr[1,:].copy()
row2 = my_arr[2,:].copy()

In [31]:
my_arr[1,:], my_arr[2,:] = row2, row1
my_arr

array([[ 0,  1,  3,  2],
       [ 8,  9, 11, 10],
       [ 4,  5,  7,  6],
       [12, 13, 15, 14]])

12 - Some os valores para cada coluna.

In [38]:
my_arr.sum(axis = 0)

array([24, 28, 36, 32])

In [37]:
for i in range(my_arr.shape[1]):
    print("Coluna",i,": ",my_arr[:,i],": sum=",my_arr[:,i].sum())

Coluna 0 :  [ 0  8  4 12] : sum= 24
Coluna 1 :  [ 1  9  5 13] : sum= 28
Coluna 2 :  [ 3 11  7 15] : sum= 36
Coluna 3 :  [ 2 10  6 14] : sum= 32


13 - Calcule a média, valor máximo e mínimo e o desvio padrão de cada row.

In [32]:
my_arr.mean(axis = 1) #média

array([ 1.5,  9.5,  5.5, 13.5])

In [34]:
my_arr.max(axis = 1) #máximo

array([ 3, 11,  7, 15])

In [35]:
my_arr.min(axis = 1) #mínimo

array([ 0,  8,  4, 12])

In [36]:
my_arr.std(axis = 1) #desvio padrão

array([1.11803399, 1.11803399, 1.11803399, 1.11803399])

In [39]:
for i in range(my_arr.shape[0]):
    print("Row ",i,": ",my_arr[i],": mean=",my_arr[i].mean(), ", max=",my_arr[i].max(),", min=",my_arr[i].min(),", sdev=",my_arr[i].std())

Row  0 :  [0 1 3 2] : mean= 1.5 , max= 3 , min= 0 , sdev= 1.118033988749895
Row  1 :  [ 8  9 11 10] : mean= 9.5 , max= 11 , min= 8 , sdev= 1.118033988749895
Row  2 :  [4 5 7 6] : mean= 5.5 , max= 7 , min= 4 , sdev= 1.118033988749895
Row  3 :  [12 13 15 14] : mean= 13.5 , max= 15 , min= 12 , sdev= 1.118033988749895


14 - Existem elementos repetidos no array?

In [40]:
elems_unique, freq = np.unique(my_arr, return_counts=True)
print(elems_unique)
print(freq )


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [42]:
if freq[freq != 1].size != 0:
    print('Existem elementos repetidos!!!')
else:
    print('Não existem elementos repetidos!!!')


Não existem elementos repetidos!!!


15 - Crie um array 3x2 contendo apenas 1s.

In [43]:
arr_0 = np.ones([3,2], dtype=int)
arr_0

array([[1, 1],
       [1, 1],
       [1, 1]])

16 - Crie um array 3x5 apenas com números random entre 0 e 20.

In [44]:
arr_r = np.random.randint(0,20,size=(3,5))
print(arr_r)

[[ 1  8 16  8  5]
 [ 9  6  8 10 19]
 [ 9 16 10 14 16]]


17 - Substraia 2 unidades a cada elemento do array anterior.

In [45]:
arr_r = arr_r - 2
print(arr_r)

[[-1  6 14  6  3]
 [ 7  4  6  8 17]
 [ 7 14  8 12 14]]


18 - Crie o array transposto do array anterior.

In [46]:
arr_r_t = arr_r.T
arr_r_t

array([[-1,  7,  7],
       [ 6,  4, 14],
       [14,  6,  8],
       [ 6,  8, 12],
       [ 3, 17, 14]])

19 - Divida o array anterior em 3 arrays.

In [47]:
arr_a, arr_b, arr_c = np.array_split(arr_r_t, 3)

In [48]:
print(arr_a)

[[-1  7  7]
 [ 6  4 14]]


In [49]:
print(arr_b)

[[14  6  8]
 [ 6  8 12]]


In [50]:
print(arr_c)

[[ 3 17 14]]


20 - Calcule o valor ao cubo (valor^3) do array transposto.

In [51]:
arr_r_t ** 3

array([[  -1,  343,  343],
       [ 216,   64, 2744],
       [2744,  216,  512],
       [ 216,  512, 1728],
       [  27, 4913, 2744]])

21 - Verifique se multiplicar o array seguinte por um outro contendo apenas 1s dá ou não os mesmos valores.

arr = [[1,2,3],[6,1,5],[1,2,9]]

In [52]:
list_nums = [[1,2,3],[6,1,5],[1,2,9]]
arr = np.array(list_nums)
arr

array([[1, 2, 3],
       [6, 1, 5],
       [1, 2, 9]])

In [53]:
np.multiply(arr, np.ones(arr.shape)) == arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

22 - Crie um array de tamanho 8, contendo números random entre 1 e 60, distribuídos seguindo uma distribuição uniforme.

In [59]:
np.random.seed(10)
arr = np.random.uniform(1,60,8)
arr



array([46.50791795,  2.22436501, 38.38524586, 45.17942907, 30.41191373,
       14.26300209, 12.68570902, 45.87131202])